#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

server:
  port: 9090
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-gateway #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379


#zuul配置
zuul:
  routes:
    ihrm-salarys: # 路由id，随便起
      path: /salarys/**   # 拦截的路径
      # url: http://127.0.0.1:9001  # 分发的地址
      service-id: ihrm-salarys
      strip-prefix: false # 不删除请求前缀
      # 处理敏感头信息，请求路由后还能携带原来的额外请求头信息
      sensitiveHeaders:
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    ihrm-company:         # 路由id，随便起
      path: /company/**   # 拦截的路径
      # url: http://127.0.0.1:9001  # 分发的地址
      service-id: ihrm-company
      strip-prefix: false # 不删除请求前缀
      # 处理敏感头信息，请求路由后还能携带原来的额外请求头信息
      sensitiveHeaders:
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    ihrm-system: #系统
      path: /sys/** #配置请求URL的请求规则
      serviceId: ihrm-system #指定Eureka注册中心中的服务id
      stripPrefix: false
      sensitiveHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    ihrm-employee: #员工
      path: /employees/** #配置请求URL的请求规则
      serviceId: ihrm-employee #指定Eureka注册中心中的服务id
      stripPrefix: false
      sensitiveHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    ihrm-social-securitys: #社保
      path: /social_securitys/** #配置请求URL的请求规则
      serviceId: ihrm-social-securitys #指定Eureka注册中心中的服务id
      stripPrefix: false
      sensitiveHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    ihrm-atte-cfg: #考勤配置项
      path: /cfg/** #配置请求URL的请求规则
      serviceId: ihrm-attendance #指定Eureka注册中心中的服务id
      stripPrefix: false
      sensitiveHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
    ihrm-atte-attendacne: #考勤
      path: /attendances/** #配置请求URL的请求规则
      serviceId: ihrm-attendance #指定Eureka注册中心中的服务id
      stripPrefix: false
      sensitiveHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头